name: Update packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update packages
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_APP_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            connect-timeout = 3
            extra-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.numtide.com
            extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=

      - name: Update packages
        run: |
          packages="$(
            nix-instantiate \
              --eval \
              --strict \
              --raw \
              -E '
                builtins.concatStringsSep "\n" (
                  builtins.attrNames (import ./default.nix)
                )
              '
          )"

          while read -r package; do
            [ -z "$package" ] && continue

            echo "::group::Update ${package}"

            nix-shell -p nix-update --run \
              "nix-update ${package} --use-update-script"

            echo "::endgroup::"
          done <<< "$packages"

      - name: Check changes
        run: git diff --check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: automation/update-packages
          delete-branch: true
          commit-message: "chore: update packages"
          title: "chore: update packages"
          body: |
            Automated package updates generated by `nix-update`.
