name: Update npins sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

concurrency:
  group: update-npins-sources
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  update:
    name: Update pinned sources
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_APP_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            connect-timeout = 3
            extra-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.numtide.com https://nix-on-droid.cachix.org
            extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g= nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=

      - name: Update npins
        run: nix run nixpkgs#npins -- update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: dependencies/npins-update
          delete-branch: true
          labels: dependencies,automated
          commit-message: "chore(deps): update npins sources"
          title: "chore(deps): update npins sources"
          body: |
            Automated weekly update of npins-pinned sources.
